1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [1]:
import numpy as np
import pandas as pd

In [3]:
dates = pd.date_range("2026-01-01", periods=40, freq="D")
df = pd.DataFrame(np.random.randint(1, 100, size=len(dates)), index=dates).astype(float)
display(df.head())

               0
2026-01-01  37.0
2026-01-02  46.0
2026-01-03  64.0
2026-01-04  70.0
2026-01-05  82.0

In [4]:
monthly_mean = df.resample("MS").mean()
display(monthly_mean)

                    0
2026-01-01  55.322581
2026-02-01  54.888889