1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.random.randint(1, 100, size=(5, 3))
df = pd.DataFrame(
    arr,
    columns=['A', 'B', 'C']
)
display(df)

    A   B   C
0  37  89  48
1  12  24  62
2  75   6  91
3  35  53  49
4  29  89   1

In [3]:
def double(x):
    return x*2

result = df.map(double)
display(result)

     A    B    C
0   74  178   96
1   24   48  124
2  150   12  182
3   70  106   98
4   58  178    2