1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Category": np.random.choice(["A", "B", "C"], size=12),
    "Values": np.random.randint(10, 100, size=12)
})
display(df)

   Category  Values
0         B      25
1         B      31
2         A      61
3         C      62
4         C      71
5         C      80
6         B      48
7         C      23
8         C      63
9         A      50
10        A      37
11        C      84

In [4]:
result = df.groupby("Category")["Values"].agg(["sum", "mean"])
display(result)

          sum       mean
Category
A         148  49.333333
B         104  34.666667
C         383  63.833333